USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO;
USE SCHEMA SOURCES;

CREATE OR REPLACE FILE FORMAT ZOMATO.SOURCES.CSV_FMT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = (' ', '\\N','NULL')
    TRIM_SPACE = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE STAGE ZOMATO.SOURCES.ZOMATO_SOURCES_STAGE
    STORAGE_INTEGRATION = ZOMATO_S3_INT
    URL = 's3://zomato-pipeline-dev-rozie/raw/'
    FILE_FORMAT = ZOMATO.SOURCES.CSV_FMT;

LIST @ZOMATO.SOURCES.ZOMATO_SOURCES_STAGE;