USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO;
USE SCHEMA SOURCES;
USE WAREHOUSE ZOMATO_WH;

-- loaded the files into stage
COPY INTO SOURCES.RESTAURANTS FROM @ZOMATO_SOURCES_STAGE/restaurants ON_ERROR = 'CONTINUE';
COPY INTO SOURCES.food FROM @ZOMATO_SOURCES_STAGE/food ON_ERROR = 'CONTINUE';
COPY INTO SOURCES.menu FROM @ZOMATO_SOURCES_STAGE/menu ON_ERROR = 'CONTINUE';
COPY INTO SOURCES.order_items FROM @ZOMATO_SOURCES_STAGE/order_items ON_ERROR = 'CONTINUE';
COPY INTO SOURCES.orders FROM @ZOMATO_SOURCES_STAGE/orders ON_ERROR = 'CONTINUE';
COPY INTO SOURCES.reviews FROM @ZOMATO_SOURCES_STAGE/reviews ON_ERROR = 'CONTINUE';
COPY INTO SOURCES.users FROM @ZOMATO_SOURCES_STAGE/users ON_ERROR = 'CONTINUE';

SELECT * FROM SOURCES.restaurants limit 10;
SELECT * FROM SOURCES.food limit 10;
SELECT * FROM SOURCES.users limit 10;

-- TRUNCATE TABLE ZOMATO.SOURCES.RESTAURANTS;
